[build]
# Dùng railpack PHP tự động, không cần builder
[build.env]
  PHP_VERSION = "8.2"

[php]
extensions = [
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "hash",
  "mbstring",
  "openssl",
  "pcre",
  "pdo",
  "session",
  "tokenizer",
  "xml",
  "gd"  # ✅ thêm extension gd
]
