[build]
builder = "railpack/php"

[packages]
php = "8.2"

[php]
extensions = [
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "hash",
  "mbstring",
  "openssl",
  "pcre",
  "pdo",
  "session",
  "tokenizer",
  "xml",
  "gd"  # ✅ thêm gd ở đây
]
